### ISSUE TITLE
iptables-restore: line 1 failed Bad argument `ACCEPT'

### ISSUE THREAD

**Issue by CHILIKE** [jackyes/IPBlocklist#1]
At the end of the script have a bug:
$IPT -I $IPTABLESCHAIN -s $1 -j ACCEPT

the error message:
iptables-restore: line 1 failed Bad argument `ACCEPT'

(op:system: centos-release-6-9.el6.12.3.x86_64)

Otherwise in the script we must re-set some directories eg IPSET="/usr/sbin/ipset", but it is normal.
Only the iptables-restore/ACCEPT string is the faulty at the end... 
Can you fix it? 
Thanks

**Comment by jackyes** [comment]
mmmm... have you created (with iptables-save) a backup of your iptables rules? Use the command:
`iptables-save > /root/iptables.save`

Doing this, the script will reload your default rules every time you run it, and then create the rules by the blocklist.

NOTE1:  you have to run iptables-save BEFORE running the script( in doubt reboot and run iptables-save before all)
NOTE2: you can use a different location to save your iptables rules, change PATHIPTABCONFIG accordingly.
